# Generated by Django 5.1.2 on 2025-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='category',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
